# -----------------------------------------------------------------------------
# Site settings
# Server settings
livereload: true
# -----------------------------------------------------------------------------

title: Jesse Zalasky
description: > # this means to ignore newlines until "baseurl:"
  My portfolio.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jessezalasky.com" # the base hostname & protocol for your site

theme: Github Template

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
